### ISSUE TITLE
[ENHANCEMENT]  Add documentation to matrix-view functions in package model.viewsudoku

### ISSUE THREAD

**Issue by hikager** [hikager/sudoku-resolver#1]
### Expected result of the enhancement
Write a clear explanation for each complex method

## Tasks
- [x]  Add clear documentation to  package model.viewsudoku
- [x] MatrixView class - method initTextBoxesMatrix()
- [x] SubMatrixView class - method initSubMatrix()
- [x] SubMatrixView class - method setProperties()
